// Embeds a curated subset of the Kenney Nature Kit GLB models (CC0) into
// src/gfx/models.js as base64 data URIs. Models are tiny (3-18 KB), so this
// keeps the game fully offline AND the single-file preview working (the
// preview inlines the JS bundle, which already contains the base64 payload).
//
// Source: vendor/kenney-nature-kit/kenney_nature_kit_glb_cc0_v1.zip
// License: CC0 (see vendor/kenney-nature-kit/License_Kenney.txt)
//
// Usage: node tools/embed_glb.mjs
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';

const __dirname = dirname(fileURLToPath(import.meta.url));
const require = createRequire(import.meta.url);
const root = resolve(__dirname, '..');

const ZIP = resolve(root, 'vendor/kenney-nature-kit/kenney_nature_kit_glb_cc0_v1.zip');
const OUT = resolve(root, 'src/gfx/models.js');

// name -> { scale, type }  (type groups for gameplay mapping)
const MANIFEST = {
  // trees (heights ~1.1-1.7 in source units; scales tuned to ~4.2-4.6 m)
  tree_default: { scale: 2.6, type: 'broad' },
  tree_default_dark: { scale: 2.6, type: 'broad' },
  tree_oak: { scale: 3.4, type: 'fruit' },
  tree_small: { scale: 2.2, type: 'sapling' },
  tree_fat: { scale: 3.4, type: 'broad' },
  tree_pineDefaultA: { scale: 2.9, type: 'pine' },
  tree_pineRoundB: { scale: 3.4, type: 'pine' },
  tree_pineTallA: { scale: 3.4, type: 'pine' },
  // rocks
  rock_largeA: { scale: 2.6, type: 'rock' },
  rock_largeB: { scale: 2.0, type: 'rock' },
  rock_smallA: { scale: 2.2, type: 'rockSmall' },
  rock_smallB: { scale: 2.2, type: 'rockSmall' },
  rock_tallA: { scale: 0.9, type: 'rockTall' },
  stone_largeA: { scale: 2.6, type: 'ore' },
  stone_smallA: { scale: 2.2, type: 'rockSmall' },
  // stumps & logs
  stump_round: { scale: 1.7, type: 'stump' },
  stump_old: { scale: 1.6, type: 'stump' },
  log: { scale: 1.9, type: 'log' },
  log_large: { scale: 1.3, type: 'logLarge' },
  // flora
  flower_purpleA: { scale: 1.5, type: 'flower' },
  flower_redA: { scale: 1.5, type: 'flower' },
  flower_yellowA: { scale: 1.5, type: 'flower' },
  plant_bushSmall: { scale: 2.2, type: 'bush' },
  plant_bush: { scale: 2.0, type: 'bush' },
  plant_flatShort: { scale: 1.8, type: 'fern' },
  plant_flatTall: { scale: 1.8, type: 'fern' },
  mushroom_red: { scale: 1.8, type: 'mushroom' },
  mushroom_tan: { scale: 2.0, type: 'mushroom' },
  grass: { scale: 1.8, type: 'grass' },
  grass_large: { scale: 2.0, type: 'grass' },
  // campfire (visual for the placed campfire)
  campfire_logs: { scale: 2.8, type: 'campfire' },
  campfire_stones: { scale: 2.2, type: 'campfire' },
};

if (!existsSync(ZIP)) {
  console.error(`missing ${ZIP}`);
  process.exit(1);
}

// minimal zip reader (no deps): local file headers + deflate via zlib
import { inflateRawSync } from 'node:zlib';

function readZipEntries(zipPath) {
  const buf = readFileSync(zipPath);
  const entries = new Map();
  let off = 0;
  const sig = (p, s) => buf.readUInt32LE(p) === s;
  const EOCD = 0x06054b50;
  const CENTRAL = 0x02014b50;
  // find EOCD
  let eocd = -1;
  for (let i = buf.length - 22; i >= 0; i--) {
    if (sig(i, EOCD)) { eocd = i; break; }
  }
  if (eocd < 0) throw new Error('no EOCD');
  const centralCount = buf.readUInt16LE(eocd + 10);
  let c = buf.readUInt32LE(eocd + 16);
  for (let i = 0; i < centralCount; i++) {
    if (!sig(c, CENTRAL)) throw new Error('bad central dir at ' + c);
    const nameLen = buf.readUInt16LE(c + 28);
    const extraLen = buf.readUInt16LE(c + 30);
    const commentLen = buf.readUInt16LE(c + 32);
    const compSize = buf.readUInt32LE(c + 20);
    const method = buf.readUInt16LE(c + 10);
    const localOff = buf.readUInt32LE(c + 42);
    const name = buf.toString('utf8', c + 46, c + 46 + nameLen);
    // local header
    const lNameLen = buf.readUInt16LE(localOff + 26);
    const lExtraLen = buf.readUInt16LE(localOff + 28);
    const dataStart = localOff + 30 + lNameLen + lExtraLen;
    const raw = buf.subarray(dataStart, dataStart + compSize);
    let data;
    if (method === 0) data = Buffer.from(raw);
    else if (method === 8) data = inflateRawSync(raw);
    else throw new Error(`unsupported method ${method} for ${name}`);
    entries.set(name, data);
    c += 46 + nameLen + extraLen + commentLen;
  }
  return entries;
}

const entries = readZipEntries(ZIP);
const out = [];
out.push('// AUTO-GENERATED by tools/embed_glb.mjs — do not edit by hand.');
out.push('// Kenney Nature Kit (CC0) embedded as base64 so the game stays offline');
out.push('// and the single-file preview works. Source: vendor/kenney-nature-kit/');
out.push('export const GLB_MODELS = {');
let total = 0;
for (const [name, spec] of Object.entries(MANIFEST)) {
  const entry = entries.get(`kenney_nature_kit_glb_cc0_v1/models_glb/${name}.glb`);
  if (!entry) {
    console.error(`MISSING in zip: ${name}.glb`);
    process.exit(1);
  }
  const b64 = entry.toString('base64');
  total += entry.length;
  out.push(`  ${JSON.stringify(name)}: { b64: ${JSON.stringify(b64)}, scale: ${spec.scale}, type: ${JSON.stringify(spec.type)} },`);
}
out.push('};');
out.push(`export const GLB_META = { count: ${Object.keys(MANIFEST).length}, bytes: ${total} };`);
writeFileSync(OUT, out.join('\n') + '\n');
console.log(`wrote ${OUT} (${Object.keys(MANIFEST).length} models, ${total} bytes -> ~${Math.round(total * 4 / 3 / 1024)} KB base64)`);
